name: myenv
dependencies:
  - python # Specify the Python version you need
  - flask
  - SQLAlchemy
  - flask-sqlalchemy
  - flask-login
  - flask-restful
  - flask-security-too
  - flask-wtf
  - flask-caching
  - redis
  - werkzeug
  - email-validator
  - pip
  - pip:
      - celery
      - flask[async]
# Install it using -
# conda env create -f environment.yml --prefix .\myenv
# For installation in local folder
# For activating the environemnt:
# conda activate ./myenv




# Start Celery Worker in wsl: In ~/household-services (working directory where main file can be found)
# celery -A main:celery_app worker -l INFO
# celery -A main:celery_app beat -l INFO


# Redis in wsl
# sudo systemctl enable redis-server                          ->           enable redis server
# sudo systemctl start redis-server                           ->           start redis server
# sudo systemctl status redis-server                          ->           status of redis server



# Start Mail hog
# ~/go/bin/MailHog
# Then go to url: 
# http://localhost:8025/
# For viewing the mails


# Open wsl filesystem fro windows explorer
# \\wsl$\Ubuntu\home\
# paste above in windows explorer